### ISSUE TITLE
Include latest hardware upgrades in the presentation

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/teo-self-presentation#11]
This repository has undergone an important rework at https://github.com/roboticslab-uc3m/teo-self-presentation/commit/19a608d6fd1680dc3f87318ba5e810435b1ea5d6. Besides CMake/C++ code review and cleanup, the apps have gained a bit of robustness (especially on application exit), and the use of IDL services should make RPC-via-terminal commanding a bit easier.

Note these changes depend on https://github.com/roboticslab-uc3m/yarp-devices/commit/df404613c731266d822346e5136c9ca680a09b33 due to the current state of the robot (broken frontal neck driver). Now, fake joints should be named like `fake-<joint_name>` in the launcher .ini file, e.g. `fake-FrontalNeck`.

As a next step, it would be nice to reflect the hardware upgrades of the last few years (e.g. new PCs). And on a side note, maybe we could also make the joint trajectories isochronous (i.e. adjust speeds so that all joints end motion at the same time)?

cc @rsantos88

**Comment by rsantos88** [comment]
Tested on the robot, It works correctly. Thanks!

**Comment by rsantos88** [comment]
Updated demostration reflecting the hardware upgrades and fixed some speaking and movement errors.
Issue closed.

**Comment by PeterBowman** [comment]
There are still a few leftovers (SSD disks, manipulation vs locomotion PCs) and grammar issues I want to review.
