### ISSUE TITLE
Sometimes, the demonstration continues freezing in salute state

### ISSUE THREAD

**Issue by rsantos88** [roboticslab-uc3m/teo-self-presentation#6]
Problem found: the demonstration continues freezing in [salute](https://github.com/roboticslab-uc3m/teo-self-presentation/blob/demo-with-plate/programs/BodyExecution/BodyExecution.cpp#L275-L300) state. 
**To do:** try to change this movement by another one that not use axial right arm

**Comment by rsantos88** [comment]
The problem of that is the differents causes of hardware errors. The function `CheckMotionDone` is cheeking all the time all the axes. I found that the **head** is normally the cause (I don't know certainly why) that `checkMotionDone` doesn't return `true` value to continues the correct performance.
So, this checking was commented at the moment.
I've done a PR(#7) to merge also the position changes with the plate.

**Comment by jgvictores** [comment]
Merged #7, saw nothing strange within it...

**Comment by rsantos88** [comment]
I'll close this issue :)
