### ISSUE TITLE
Update joint-space commands

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-self-presentation#8]
Update joint-space commands, changed at https://github.com/roboticslab-uc3m/teo-main/issues/39

**Comment by rsantos88** [comment]
Tested on teoSim: https://github.com/roboticslab-uc3m/teo-self-presentation/pull/9

**Comment by jgvictores** [comment]
Done at https://github.com/roboticslab-uc3m/teo-self-presentation/pull/9, merge commit https://github.com/roboticslab-uc3m/teo-self-presentation/commit/29aa32a75e929b4cc90f6a63c772be388dea858b

THANKS!!!!!!
